on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Clean my PRs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./
        id: hello
        with:
          githubToken: 'Zack'
