on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello wold action step
        id: hello
        uses: actions/so-clean@v1
        with:
          who-to-greet: 'Zack'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outpus.time }}"
